apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prometheus
spec:
  tls:
    - hosts:
      - metrics.dd-decaf.eu
      secretName: decaf-tls
  rules:
  - host: metrics.dd-decaf.eu
    http:
      paths:
      - path: /
        backend:
          serviceName: prometheus
          servicePort: 3000
